use budget;

GRANT EXECUTE ON PROCEDURE SELECT_ACCOUNTS TO 'budget'@'localhost';
GRANT EXECUTE ON PROCEDURE SELECT_CATEGORIES TO 'budget'@'localhost';
GRANT EXECUTE ON PROCEDURE SELECT_CURRENT_ACCOUNT_BALANCES TO 'budget'@'localhost';
GRANT EXECUTE ON PROCEDURE SELECT_ENTRY TO 'budget'@'localhost';
GRANT EXECUTE ON PROCEDURE SELECT_EXPENSES TO 'budget'@'localhost';
GRANT EXECUTE ON PROCEDURE SELECT_EXPENSES_BY_MONTHS TO 'budget'@'localhost';
GRANT EXECUTE ON PROCEDURE SELECT_INCOMES TO 'budget'@'localhost';
GRANT EXECUTE ON PROCEDURE SELECT_SUBCATEGORIES TO 'budget'@'localhost';
GRANT EXECUTE ON PROCEDURE SELECT_TRANSFER TO 'budget'@'localhost';
GRANT EXECUTE ON PROCEDURE SELECT_TRANSFERS TO 'budget'@'localhost';

GRANT EXECUTE ON PROCEDURE UPDATE_ENTRY TO 'budget'@'localhost';
GRANT EXECUTE ON PROCEDURE UPDATE_TRANSFER TO 'budget'@'localhost';

GRANT EXECUTE ON PROCEDURE INSERT_TRANSFER TO 'budget'@'localhost';






    
